### PR TITLE
Why give someone you don't trust admin permission?

### PR DESCRIPTION
**Pull request by ThatJerk**
You shouldn't give someone who you don't trust them enough to not do anything stupid an administrator permission 
so it is all your fault therefore you deserved this,
I hope this will teach you a lesson.

### CODE REVIEW

**Comment by remotevase** [comment]
Oh, we trusted him alright

**Comment by Taki21** [comment]
We didn't deserve this and u we already know our lesson its pretty obtainable with common sense.
Please reconsider what you are saying before saying something wrong.

**Comment by remotevase** [comment]
Wow @DALTONTASTIC reacted with a :heart: emoji

**Comment by Riegert** [comment]
@DALTONTASIC , I don't care if you told @ThatJerk to post that. Your going on about a battle that you did not win. You said you ''hacked'' ImagicalMine. That doesn't stop us from doing what we do. Your 19, but your acting like a 1 year old child. Say whatever you want to say, just know that it's pure utter crap that comes out of your mouth. I don't give a damn about your twitter feed. That does not stop ImagicalMine. Go on about how you killed ImagicalMine, even though you didn't. Enjoy your laugh, even though there is nothing to laugh at. Let me just tell you one thing, and just one thing, grow up. You can't be a 1 year old child forever.

**Comment by TheKillerTacos** [comment]
Thats the main problem, they trusted the wrong person, even if its their faut, it doesnt matter, In this world No one seems to be who they think they are, So in this world No one trust anyone, if you even win any Trust on someone, Keep aware that he may betray (idk if its wroten correctly) you and make bad things, or good, But No one knows the people they want to trust on.

**Comment by Taki21** [comment]
Once i have perm, I will lock and close this and put Invalid Tags

**Pull request closed without merging**
