### PR TITLE
Update users.md

### PR DESCRIPTION
**Pull request by Falkirks**
[cleared]

### CODE REVIEW

**Comment by ProjectInfinity** [comment]
@Falkirks boo. These people are dumb for giving administrator rights to random people, you should know better. Justice has already been served, it's called natural selection.

**Comment by Ad5001** [comment]
@ProjectInfinity The guy who did that actually created ImagicalMine home page website. I think that's why they give him permissions

**Comment by Falkirks** [comment]
@ProjectInfinity They made a mistake, I know that. They should have been more careful. I really think that they need to learn a lesson about security and responsibility. I have very little respect for them or their decision to give @DALTONTASTIC admin rights. However, I sign this letter for other reasons. First, I believe in supporting a free and open source community. @DALTONTASTIC made an attack against my freedom to browse and examine the ImagicalMine source code. This is serious and I believe that the MCPE community deserve remedy. I don't believe that ImagicalMine deserves anything: I sign for the users, other developers, and players who have been disrupted by this action. Second, I don't support @DALTONTASTIC's childish game of deleting repositories and name calling and such. I think that ImagicalMine has dealt with the situation with some grace and I commend them for that. Third, I don't want @DALTONTASTIC to be in control of name which belongs to a large open-source project. That seems dangerous and unwise.

Please don't jump to conclusions: natural selection is important, but if it means our community falling apart, I will fight it.

**Comment by Falkirks** [comment]
After re-reading the letter and what has been written. I do **not** support any petition to ban @DALTONTASTIC. However, I strongly support the recovery of repositories. If the letter is amended, I will sign.

**Comment by applqpak** [comment]
@Falkirks Thanks for helping support.

@ProjectInfinity I know, and they know, it was a huge mistake. But hey, who here, living, hasn't made a mistake?

**Pull request closed without merging**
