### PR TITLE
Me

### PR DESCRIPTION
**Pull request by SkygridRex**
Dear @github,
I decided to sign this letter because I solely believe that this is unfair.
Why should such a big community like the ImagicalMine community just disappear like this? I hope that this "hacker", or admin rights abuser will be banned, and this message to be showed to any other rights abuser that they will be banned and that they should learn a lesson. Please help the @ImagicalCorporation achieve what they have asked for, as I am a proud supporter with them. Thank you GitHub, for all that you do for us.

### CODE REVIEW

**Comment by SkygridRex** [comment]
@TheKillerTacos Please Help

**Comment by keithkfng** [comment]
Adding your name on manually.

**Comment by SkygridRex** [comment]
Can you Explain me?

**Comment by keithkfng** [comment]
You're on, I added you, it's just because the PR had conflicts.

**Comment by SkygridRex** [comment]
@keithkfng If you don't want my help i could understand you, no has feelings man ;)

**Comment by keithkfng** [comment]
I already have added your name -_-
https://github.com/ImagicalCorp/dear-github/blob/master/users.md

**Comment by SkygridRex** [comment]
Oh My Herman! Someone has written well my  username

**Pull request closed without merging**
